# Generated by Django 3.1.1 on 2020-09-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('bugName', models.CharField(max_length=240, verbose_name='Bug')),
                ('bugDescription', models.CharField(max_length=1000, verbose_name='Description')),
                ('project', models.CharField(max_length=240, verbose_name='Project Description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
